#!/usr/bin/env python3
"""reducer.py"""

from operator import itemgetter
import sys

destination = None
current_airport = None
sumdelay = 0
denom = 1

# input comes from STDIN
for line in sys.stdin:
    # remove leading and trailing whitespace
    line = line.strip()

    # parse the input we got from mapper.py
    destination, airport, delay = line.split('\t', 1)
    
    if current_airport == airport:
        sumdelay += int(delay)
        denom += 1
    else:
        if current_airport:
            print(destination + current_airport + "\t" + str(sumdelay/denom))
        current_airport = airport
        sumdelay = 0
        denom = 1
            
if current_airport == airport:
    print(current_airport + "\t" + str(sumdelay/denom))
        
    
    
